### ISSUE TITLE
v1.1.1 not accessible on GitHub

### ISSUE THREAD

**Issue by jurajlutter** [leighmcculloch/go-tz#2]
Hi,

beats 7.8.1 requires go-tz `v1.1.1-0.20191124060701-6d37baae851b` and it is not available here on GitHub.

I am working on FreeBSD port and need this file to be downloaded from GH (as part of `fetch` stage, later the build does not have the network access so it can't download the file from the Internet, among other reasons.)

Would it be possible, please?

Thanks.

**Comment by leighmcculloch** [comment]
There has never been a `v1.1.1` of this library. The commit you reference, `6d37baae851b`, is the commit for master that hasn't been released yet. I'm not sure why `beats` is referencing it as `v1.1.1`. I'm happy to tag it as such though. I can tag it tonight 👍.

**Comment by leighmcculloch** [comment]
I've just taken more of a look and it appears that Go modules is working the way it is supposed to. Version `v1.1.1-0.20191124060701-6d37baae851b` is the unreleased next version that thereotically will be released from `master` and is pointing at commit 6d37baae851b6f07225308b199322f70907aa3dd.

So if you need to fetch the code for `4d63.com/tz` at that version, you can, that commit is in the history. It is currently the latest commit on `master`.

There's a good article about how pseudo-versions work in Go here:
https://jfrog.com/blog/go-big-with-pseudo-versions-and-gocenter/

The most relevant part is the third dot-point in this:
>There are 3 acceptable forms of pseudo-version :
>
>- vX.0.0-yyyymmddhhmmss-abcdefxyz when no earlier versioned commit with an appropriate major version before target commit
>- vX.Y.Z-pre.0.yyyymmddhhmmss-abcdefxyz when most recent versioned commit before the target commit is vX.Y.Z-pre
>- vX.Y.(Z+1)-0.yyyymmddhhmmss-abcdefxyz when most recent versioned commit before the target commit is vX.Y.Z

**Comment by jurajlutter** [comment]
I need to fetch it by means of https as file from github.

**Comment by leighmcculloch** [comment]
Every commit can be fetched. For example: https://github.com/leighmcculloch/go-tz/archive/6d37baae851b6f07225308b199322f70907aa3dd.zip
